### PR TITLE
Updated for Gnome 3.18

### PR DESCRIPTION
**Pull request by macleodsawyer**

### CODE REVIEW

**Comment by danielkza** [comment]
Have you been able to test in 3.18? Does everything work? I'll probably try to get a Fedora Rawhide VM to check it out soon, and then I'll updated the metadata.

**Comment by macleodsawyer** [comment]
Everything works perfectly in 3.18 as long as the metadata is updated.

Been using it in 3.18 for atleast two weeks now and have had no issues
stemming from it.

On Mon, Sep 21, 2015, 04:57 Daniel Miranda <notifications@github.com> wrote:

> Have you been able to test in 3.18? Does everything work? I'll probably
> try to get a Fedora Rawhide VM to check it out soon, and then I'll updated
> the metadata.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danielkza/Gnome-Shell-Window-Buttons-Extension/pull/1#issuecomment-141929165>
> .
>
-- 

-- 
Macleod Sawyer
http://macleodsawyer.com/
Founder of CharityDrops.org

**Comment by danielkza** [comment]
I'll make a release on extensions.gnome.org ASAP. Thanks!

**Comment by danielkza** [comment]
The new version should be up after it's gone through the review process. Thanks again.

**Pull request merged**
