### PR TITLE
Shell 3.20 compatibility

### PR DESCRIPTION
**Pull request by dffischer**
The extension loads without issues and adds buttons as expected, so I request adding 3.20 to the list of supported versions.

### CODE REVIEW

**Comment by unfulvio** [comment]
+1

**Comment by danielkza** [comment]
Sorry for taking so long, I completely missed this among my notifications.

**Comment by dffischer** [comment]
Thanks for the merge.

Perhaps I may point you to [the related pull request for MaximusTwo](https://github.com/danielkza/GnomeExtensionMaximusTwo/pull/1) in case it was also just forgotten.

**Comment by danielkza** [comment]
v15 is up on http://extensions.gnome.org with this PR. Thanks a lot!

**Pull request merged**
